# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('76db9147efe9ab43e4e5461f9a26c75b_MTU1OTQyMjAxMi0xMS0xNiAwMDowNToyOS45NjE3NDE')
  end)
end
